-- =============================================================================
-- RENTFLOW / ATLASFLEET SAAS - FLYWAY MIGRATION V1__init_schema.sql
-- =============================================================================

CREATE TABLE IF NOT EXISTS tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    subdomain VARCHAR(255) NOT NULL UNIQUE,
    ice_number VARCHAR(255),
    if_number VARCHAR(255),
    rc_number VARCHAR(255),
    patente_number VARCHAR(255),
    tva_rate DOUBLE PRECISION DEFAULT 20.0,
    address VARCHAR(255),
    city VARCHAR(255),
    phone VARCHAR(255),
    email VARCHAR(255),
    logo_url VARCHAR(255),
    subscription_plan VARCHAR(50) DEFAULT 'PRO',
    subscription_status VARCHAR(50) DEFAULT 'ACTIVE',
    subscription_end DATE,
    max_vehicles INT DEFAULT 50,
    monthly_price DOUBLE PRECISION DEFAULT 450.0,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    phone VARCHAR(255),
    role VARCHAR(50) NOT NULL,
    tenant_id BIGINT,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    registration_number VARCHAR(255) NOT NULL,
    registration_type VARCHAR(50),
    brand VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    finish VARCHAR(255),
    vehicle_year INT,
    fuel_type VARCHAR(50),
    gearbox VARCHAR(50),
    current_mileage DOUBLE PRECISION,
    daily_rate DOUBLE PRECISION,
    status VARCHAR(50),
    photo_url VARCHAR(500),
    grey_card_url VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vehicles_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE IF NOT EXISTS vehicle_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL,
    doc_type VARCHAR(100),
    expiration_date DATE,
    document_url VARCHAR(500),
    provider_name VARCHAR(255),
    cost DOUBLE PRECISION,
    alert_sent BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_documents_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS maintenance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL,
    service_type VARCHAR(100),
    service_date DATE,
    mileage_at_service DOUBLE PRECISION,
    next_service_mileage DOUBLE PRECISION,
    next_service_date DATE,
    cost DOUBLE PRECISION,
    garage_name VARCHAR(255),
    notes VARCHAR(1000),
    status VARCHAR(50),
    CONSTRAINT fk_maintenance_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    client_type VARCHAR(50),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    cin_passport VARCHAR(255),
    cin_expiry_date DATE,
    driver_license_number VARCHAR(255),
    driver_license_expiry DATE,
    driver_license_obtained_date DATE,
    phone_whats_app VARCHAR(255),
    email VARCHAR(255),
    nationality VARCHAR(255),
    company_name VARCHAR(255),
    ice_number VARCHAR(255),
    if_number VARCHAR(255),
    rc_number VARCHAR(255),
    designated_driver_name VARCHAR(255),
    designated_driver_cin VARCHAR(255),
    cin_scan_front_url VARCHAR(500),
    cin_scan_back_url VARCHAR(500),
    license_scan_url VARCHAR(500),
    risk_score INT DEFAULT 90,
    blacklisted BOOLEAN DEFAULT FALSE,
    blacklist_reason VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_clients_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE IF NOT EXISTS reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    vehicle_id BIGINT NOT NULL,
    client_id BIGINT NOT NULL,
    reservation_number VARCHAR(255) NOT NULL UNIQUE,
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    pickup_location VARCHAR(255),
    return_location VARCHAR(255),
    rate_season VARCHAR(50),
    daily_rate DOUBLE PRECISION,
    total_days BIGINT,
    options_amount DOUBLE PRECISION DEFAULT 0.0,
    total_amount DOUBLE PRECISION DEFAULT 0.0,
    deposit_amount DOUBLE PRECISION DEFAULT 0.0,
    paid_amount DOUBLE PRECISION DEFAULT 0.0,
    payment_method VARCHAR(50),
    options_json VARCHAR(2000),
    status VARCHAR(50) DEFAULT 'CONFIRMEE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reservations_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_reservations_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_reservations_client FOREIGN KEY (client_id) REFERENCES clients(id)
);

CREATE TABLE IF NOT EXISTS inspections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    reservation_id BIGINT NOT NULL,
    vehicle_id BIGINT NOT NULL,
    type VARCHAR(50),
    mileage DOUBLE PRECISION,
    fuel_level VARCHAR(50),
    damage_markers_json TEXT,
    photo_urls_json TEXT,
    caution_amount DOUBLE PRECISION,
    caution_type VARCHAR(50),
    caution_status VARCHAR(50),
    extra_fees_amount DOUBLE PRECISION DEFAULT 0.0,
    extra_fees_notes VARCHAR(500),
    signature_base64 TEXT,
    pdf_contract_url VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inspections_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_inspections_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id),
    CONSTRAINT fk_inspections_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
);

CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    reservation_id BIGINT,
    client_id BIGINT NOT NULL,
    invoice_number VARCHAR(255) NOT NULL UNIQUE,
    ice_agency VARCHAR(255),
    if_agency VARCHAR(255),
    rc_agency VARCHAR(255),
    ice_client VARCHAR(255),
    totalht DOUBLE PRECISION,
    tva_rate DOUBLE PRECISION DEFAULT 20.0,
    totaltva DOUBLE PRECISION,
    totalttc DOUBLE PRECISION,
    payment_status VARCHAR(50) DEFAULT 'PAYEE',
    pdf_invoice_url VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_invoices_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_invoices_client FOREIGN KEY (client_id) REFERENCES clients(id)
);

CREATE TABLE IF NOT EXISTS cash_register_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    shift_start TIMESTAMP,
    shift_end TIMESTAMP,
    starting_cash DOUBLE PRECISION DEFAULT 0.0,
    total_cash_received DOUBLE PRECISION DEFAULT 0.0,
    total_tpe_received DOUBLE PRECISION DEFAULT 0.0,
    total_check_received DOUBLE PRECISION DEFAULT 0.0,
    total_transfer_received DOUBLE PRECISION DEFAULT 0.0,
    expected_cash_in_hand DOUBLE PRECISION DEFAULT 0.0,
    actual_cash_in_hand DOUBLE PRECISION DEFAULT 0.0,
    cash_difference DOUBLE PRECISION DEFAULT 0.0,
    status VARCHAR(50) DEFAULT 'OUVERT',
    notes VARCHAR(500),
    CONSTRAINT fk_cash_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_cash_user FOREIGN KEY (user_id) REFERENCES app_users(id)
);

CREATE TABLE IF NOT EXISTS radar_fines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    vehicle_id BIGINT NOT NULL,
    client_id BIGINT,
    ticket_number VARCHAR(255),
    violation_date TIMESTAMP,
    violation_location VARCHAR(255),
    fine_amount DOUBLE PRECISION,
    reallocated BOOLEAN DEFAULT FALSE,
    reallocation_date TIMESTAMP,
    status VARCHAR(50) DEFAULT 'RECU',
    CONSTRAINT fk_radars_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_radars_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_radars_client FOREIGN KEY (client_id) REFERENCES clients(id)
);
